name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u kianisnotavailable -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t kianisnotavailable/twitch_bot:latest .
        docker push kianisnotavailable/twitch_bot:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS CLI
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region eu-north-1

    - name: Update Elastic Beanstalk environment
      run: |
        COMMIT_SHA=$(git rev-parse --short HEAD)
        aws elasticbeanstalk create-application-version --application-name freeleetcodecamp --version-label $COMMIT_SHA --source-bundle S3Bucket=twitchbot-bucket,S3Key=Dockerrun.aws.json
        aws elasticbeanstalk update-environment --application-name freeleetcodecamp --environment-name twitchbot --version-label $COMMIT_SHA
